name: CI
on: 
    push:
        branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: truesne/wdiogithub
    steps:
      - name: Test
        run: cd /app && npm run test:chrome:headless:login
# name: ci
# on:
#   push:
#     branches:
#       - 'master'

# jobs:
#     compile:
#         name: Compile site assets
#         runs-on: ubuntu-latest
#         steps:
#           - name: Check out the repo
#             uses: actions/checkout@v2
#           - name: Run the build process with Docker
#             uses: addnab/docker-run-action@v3
#             with:
#                 image: truesne/wdiotelnyxtest
#                 options: -v ${{ github.workspace }}:/var/www
#                 run: |
#                     composer install
#                     npm install
#                     npm run test:chrome:headless:login
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout 
#         uses: actions/checkout@v2
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wdiotelnyxtestrun