name: CI
on: 
    push:
        branches: [master]
jobs:
  build:
    image: truesne/wdiotelnyxtest
      # - name: docker test
      #   uses: docker://truesne/wdiotelnyxtest
        - name: Test
          # run: npm run test:firefox:headless
          # run: npm run test:chrome:headless
          run: npm run test:chrome:headless:login


        